# Generated by Django 6.0.3 on 2026-03-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("master", "마스터"),
                    ("viewer", "일반조회자"),
                    ("pending", "승인대기"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
