version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: jsyouth_backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
      - ./Backend/db.sqlite3:/app/db.sqlite3
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=*
      # AWS 배포 후엔 사용할 도메인을 ALLOWED_HOSTS에 기입해야 정상 작동합니다.

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: jsyouth_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
